-- MICRA CSE schema reconciliation
-- STATUS: LEGACY / NON-CANONICAL. DO NOT EXECUTE.
--
-- The live MICRA Supabase database is the canonical schema for CSE/WP-01.
-- Canonical survey table: public.survey_records
-- Canonical evidence table: public.evidence_records
-- Canonical verification: public.verification_records
-- Canonical baseline: public.baseline_records
-- Canonical GEF evidence: public.gef_evidence_records
--
-- The historical public.cse_surveys bootstrap schema below is intentionally
-- retired. It used uppercase statuses and anonymous allow-all RLS policies.
-- It MUST NOT be recreated or used by the application.
--
-- Live migration history:
-- 20260829054644  micra_cse_field_survey_v1_1
-- 20260904082811  r0_runtime_foundation_security
-- 20260904084318  phase2_wp01_evidence_workflow
--
-- Important reconciliation note:
-- survey_records is the sole CSE write path. The live database contains
-- micra_sync_survey_evidence(), which synchronizes evidence_records.
-- The repository frontend therefore must not insert evidence_records directly.
--
-- No Supabase DDL is performed by this repository reconciliation patch.
