'use client';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Farm={id:string;farm_code:string;name:string;cluster_id:string|null};
export default function SurveyForm({farms}:{farms:Farm[]}){
 const [farmId,setFarmId]=useState(farms[0]?.id||''); const [notes,setNotes]=useState(''); const [lat,setLat]=useState(''); const [lon,setLon]=useState(''); const [accuracy,setAccuracy]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 function gps(){if(!navigator.geolocation)return setMessage('Geolocation is not supported by this browser.'); setMessage('Acquiring GPS…'); navigator.geolocation.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLon(String(p.coords.longitude));setAccuracy(String(Math.round(p.coords.accuracy)));setMessage('GPS captured.');},e=>setMessage(e.message),{enableHighAccuracy:true,timeout:15000});}
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage(''); const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href='/login';return;} const farm=farms.find(f=>f.id===farmId); if(!farm){setMessage('Select a farm.');setLoading(false);return;} const evidenceId=`WP01-${Date.now()}`; const {error}=await supabase.from('survey_records').insert({evidence_id:evidenceId,farm_id:farm.id,cluster_id:farm.cluster_id,observer_id:user.id,survey_timestamp:new Date().toISOString(),latitude:lat?Number(lat):null,longitude:lon?Number(lon):null,gps_accuracy_m:accuracy?Number(accuracy):null,payload:{field_notes:notes},status:'raw',confidence:'medium'}); if(error)setMessage(error.message); else {setMessage(`Saved ${evidenceId}.`);setNotes('');} setLoading(false); }
 return <form className="panel" onSubmit={submit}><div className="formGrid"><label>Farm<select required value={farmId} onChange={e=>setFarmId(e.target.value)}>{farms.map(f=><option key={f.id} value={f.id}>{f.farm_code} · {f.name}</option>)}</select></label><label>GPS latitude<input value={lat} onChange={e=>setLat(e.target.value)} inputMode="decimal"/></label><label>GPS longitude<input value={lon} onChange={e=>setLon(e.target.value)} inputMode="decimal"/></label><label>GPS accuracy (m)<input value={accuracy} onChange={e=>setAccuracy(e.target.value)} inputMode="decimal"/></label><label className="full">Field observations<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record observable baseline facts…" rows={6}/></label></div><div className="formActions"><button type="button" className="secondary" onClick={gps}>Capture GPS</button><button className="primary" disabled={loading||!farms.length}>{loading?'Saving…':'Save raw assessment'}</button></div>{message&&<div className="formNotice">{message}</div>}</form>;
}
